services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agrix
#  mysql:
#    image: mysql:8.0.32
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root