# fly.toml app configuration file generated for agrix-farms on 2024-10-25T10:39:08-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agrix-farms'
primary_region = 'gru'

swap_size_mb = 512

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
